#define TAC_CIVILIAN_VEHICLES ["C_Van_01_fuel_F","C_Hatchback_01_F","C_Hatchback_01_sport_F","C_Offroad_02_unarmed_F","C_Offroad_02_unarmed_F_black", "C_Offroad_02_unarmed_F_blue","C_Offroad_02_unarmed_F_green","C_Offroad_02_unarmed_F_orange","LandRover_TK_CIV_EP1","C_Offroad_01_F", "C_SUV_01_F","C_Van_01_transport_F","C_Van_01_box_F","C_Truck_02_fuel_F","C_Truck_02_box_F","C_Truck_02_transport_F","C_Truck_02_covered_F","C_Boat_Civil_01_rescue_F", "C_Rubberboat", "C_Boat_Transport_02_F", "C_Scooter_Transport_01_F", "MU_CIV_Mohawk", "C_Heli_Light_01_civil_F", "MU_CIV_HummingBird_blueline", "MU_CIV_HummingBird_blue", "MU_CIV_HummingBird_elliptical", "MU_CIV_HummingBird_furious", "MU_CIV_HummingBird_graywatcher", "MU_CIV_HummingBird_jeans", "MU_CIV_HummingBird_redviolet", "MU_CIV_HummingBird_shadow", "MU_CIV_HummingBird_sheriff", "MU_CIV_HummingBird_speedy", "MU_CIV_HummingBird_sunset", "MU_CIV_HummingBird_vrana", "MU_CIV_HummingBird_wasp", "MU_CIV_HummingBird_wave", "MU_CIV_Orca", "C_Plane_Civil_01_F", "C_Plane_Civil_01_racing_F", "MELB_MH6M"] // Remove MELB_MH6M when mission over.

#define TAC_CIVILIAN_UNIFORMS ["U_Afghan01NH", "U_Afghan02NH", "U_Afghan03NH", "U_Afghan06NH", "U_I_C_Soldier_Bandit_4_F", "U_I_C_Soldier_Bandit_1_F", "U_I_C_Soldier_Bandit_2_F", "U_I_C_Soldier_Bandit_3_F", "U_I_C_Soldier_Bandit_5_F", "U_C_Man_casual_2_F", "U_C_Man_casual_1_F", "U_C_Man_casual_3_F", "U_MU_PoloshirtPants2", "U_MU_PoloshirtPants1", "tacs_Uniform_Combat_LS_CDBS_GP_TB", "tacs_Uniform_Combat_LS_CLBS_GP_BB", "tacs_Uniform_Combat_LS_CLRS_TP_BB", "tacs_Uniform_Combat_LS_CPS_BP_BB", "tacs_Uniform_Combat_RS_CDBS_GP_TB", "tacs_Uniform_Combat_RS_CLBS_GP_BB", "tacs_Uniform_Combat_RS_CLRS_TP_BB", "tacs_Uniform_Combat_RS_CPS_BP_BB", "U_C_Poloshirt_blue", "U_C_Poloshirt_burgundy", "U_C_Poloshirt_redwhite", "U_C_Poloshirt_salmon", "U_C_Poloshirt_stripped", "U_C_Poloshirt_tricolour", "U_BG_Guerilla2_2", "U_BG_Guerilla2_1", "U_BG_Guerilla2_3", "U_BG_Guerilla3_1", "U_OrestesBody", "U_Marshal", "U_C_man_sport_1_F", "U_C_man_sport_3_F", "U_C_man_sport_2_F", "U_C_Man_casual_6_F", "U_C_Man_casual_4_F", "U_C_Man_casual_5_F", "tacs_Uniform_Polo_CP_LS_TP_OB", "tacs_Uniform_Polo_CP_RS_LP_BB", "tacs_Suit_VIP", "U_C_Journalist", "U_B_Wetsuit", "U_MU_B_GuerillaGarment2", "U_MU_B_GuerillaGarment2_blue", "U_MU_B_GuerillaGarment2_brown", "U_MU_B_GuerillaGarment2_grey", "U_MU_B_GuerillaGarment2_redcamo", "U_MU_B_GuerillaGarment2_orange", "U_MU_B_GuerillaGarment2_skull", "U_MU_B_GuerillaGarment2_yellow"]

#define TAC_CIVILIAN_HEADGEAR ["", "Afghan_01Hat", "Afghan_02Hat", "Afghan_03Hat", "Afghan_04Hat", "Afghan_05Hat", "Afghan_06Hat", "H_Bandanna_gry", "H_Bandanna_blu", "H_Bandanna_cbr", "H_Bandanna_khk", "H_Bandanna_sgg", "H_Bandanna_sand", "H_Bandanna_surfer", "H_Bandanna_surfer_blk", "H_Bandanna_surfer_grn", "H_Cap_blk", "H_Cap_blu", "H_Cap_grn", "H_Cap_red", "H_Cap_surfer", "H_Hat_brown", "H_Hat_checker", "H_Hat_grey", "H_Hat_tan", "H_Shemag_olive", "H_ShemagOpen_tan", "H_ShemagOpen_khk", "tacs_Hat_Boonie_RangerGreen", "H_Booniehat_khk", "H_Booniehat_oli", "H_Booniehat_tan", "H_Cap_oli", "H_Cap_press", "H_Cap_tan", "H_Cap_khaki_specops_UK", "H_Cap_usblack", "H_Hat_blue", "H_Cap_marshal", "H_Cap_headphones", "H_Helmet_Skate", "H_RacingHelmet_1_black_F", "H_RacingHelmet_1_blue_F", "H_RacingHelmet_2_F", "H_RacingHelmet_1_F", "H_RacingHelmet_1_green_F", "H_RacingHelmet_1_orange_F", "H_RacingHelmet_1_red_F", "H_RacingHelmet_3_F", "H_RacingHelmet_4_F", "H_RacingHelmet_1_white_F", "H_RacingHelmet_1_yellow_F"]

#define TAC_CIVILIAN_BACKPACKS ["", "B_AssaultPack_blk", "B_AssaultPack_cbr", "B_AssaultPack_rgr", "B_AssaultPack_khk", "B_AssaultPack_sgg", "B_FieldPack_blk", "B_FieldPack_cbr", "B_FieldPack_khk", "B_FieldPack_oli", "B_MU_Kitbag_blk", "B_Kitbag_cbr", "tacs_Backpack_Kitbag_DarkBlack", "B_Kitbag_rgr", "B_Kitbag_sgg", "ACE_NonSteerableParachute", "B_Parachute", "B_TacticalPack_blk", "B_MU_TacticalPack_cbr", "B_TacticalPack_rgr", "B_TacticalPack_oli"]

#define TAC_CIVILIAN_VESTS ["", "V_Press_F", "V_RebreatherB", "lbt_pouchless_od", "lbt_pouchless_coy"]

#define TAC_CIVILIAN_GLASSES ["", "G_Aviator", "G_Bandanna_aviator", "G_Bandanna_blk", "G_Bandanna_khk", "G_Bandanna_oli", "G_Bandanna_shades", "G_Bandanna_sport", "G_Bandanna_tan", "G_Shades_Black", "G_Shades_Blue", "G_Shades_Green", "G_Shades_Red", "G_Spectacles", "G_Sport_Red", "G_Sport_Blackyellow", "G_Sport_BlackWhite", "G_Sport_Checkered", "G_Sport_BlackredG_Sport_Greenblack", "G_Squares_Tinted", "G_Squares", "G_Spectacles_Tinted", "tacs_goggles_black", "tacs_Goggles_Green", "tacs_Goggles_Tan"]

#define TAC_CIVILIAN_REDZONES ["dis_bl1", "dis_bl2", "dis_bl3", "dis_bl4"]